### ISSUE TITLE
A live demo with gh-pages

### ISSUE THREAD

**Issue by ChanMenglin** [wiwikuan/wiwi-circleOfFifths#5]
https://chanmenglin.github.io/wiwi-circleOfFifths/

**Comment by J7503303** [comment]
为什么我本地运行不了呢？你这个链接没问题。

**Comment by ChanMenglin** [comment]
可以运行，您可以根据[这页](https://pages.github.com)(Project site > Start from scratch)的内容在自己的仓库中设置

**Comment by ganjiayi** [comment]
好的，我试试，非常感谢！对了，你也是玩音乐的？

**Comment by J7503303** [comment]
好的，我试试，非常感谢！对了，你也是玩音乐的？

**Comment by ChanMenglin** [comment]
不客气，我只是对音乐有些兴趣，不太懂
